### ISSUE TITLE
Opening pandora.com crashes firefox

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-echo-show#119]
https://github.com/mozilla-mobile-skunkworks/firefox-connect/issues/569

**Comment by mcomella** [comment]
I can't reproduce this. Notably, the top of the page says, "...on the all-new Pandora": maybe they just rewrote the page.

Unfortunately, it looks like you can't access pandora on mobile anymore now: "Open pandora" does nothing (it tries to open the app and we disabled that) and "Get the App" takes you to google play.

I was unable to reproduce by:
- Using our quick, "Request desktop site" solution (removing "Mobile" from "Mobile Safari")
- Using the desktop Firefox user agent, even after playing music content

---

@rpappalax Can you reproduce? If not, please close.

**Comment by rpappalax** [comment]
Unable to repro, so closing
