### ISSUE TITLE
Upgrade to kotlin 1.3

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-echo-show#148]
We need to support kotlin 1.3, in particular the breaking changes from coroutines, in order to copy the `PinnedTilesRepo` into this project from Fire TV (which will eventually be exported to components).

**Comment by athomasmoz** [comment]
Let's do this at the same time as #100

**Comment by mcomella** [comment]
Bad news bears! Components throws an error after the upgrade:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/experimental/android/HandlerContextKt;
        at mozilla.components.browser.domains.DomainAutoCompleteProvider.initialize(DomainAutoCompleteProvider.kt:119)
        at mozilla.components.browser.domains.DomainAutoCompleteProvider.initialize$default(DomainAutoCompleteProvider.kt:113)
        at org.mozilla.focus.toolbar.ToolbarIntegration.initTextChangeListeners(ToolbarIntegration.kt:247)
        at org.mozilla.focus.toolbar.ToolbarIntegration.setup(ToolbarIntegration.kt:104)
```

Looking at the code, it fails using an old version of coroutines:
```kotlin
            launch(UI) {
                val domains = async(CommonPool) { Domains.load(context) }
                val customDomains = async(CommonPool) { CustomDomains.load(context) }

                onDomainsLoaded(domains.await(), customDomains.await())
            }
```

I'm guessing we can't have both versions of coroutines at the same time: we'll need to upgrade to components 0.31, which was compiled against the new coroutines, for this to work.

**Comment by mcomella** [comment]
I have a WIP that has tests and appears to work in the UI: https://github.com/mozilla-mobile/firefox-echo-show/tree/148-mcomella-kotlin13

Still TODO: I need to verify that cancellation works as expected (e.g. by adding extremely large `delay`s and verifying the behavior works as I think it should). @Baron-Severin FYI

**Comment by mcomella** [comment]
QA: this change is upgrading a dependency with non-trivial breaking changes. The risky areas are asynchronous code around:
- Fetching custom home tile content
- Making the progress bar hide itself

The risk is these may not function correctly or may cause a memory leak (if you know how to test that). Please verify, within regular use cases, that these changes look correct.
