### ISSUE TITLE
"Open Pandora" link is inert on pandora.com site

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/firefox-echo-show#149]
## Steps to reproduce
1. Go to pandora.com
2. Click on "Open Pandora"

### Expected behavior
2. Not sure, since Pandora app not supported?

### Actual behavior
2. Link is inert

### NOTES
If I say "Alexa open pandora"
reply is: "the pandora skill is not enabled.  Go to the Alexa app to enable it and link your account."

see similar issues:
functions shown don't work on device - ikea.com: cannot "save", "print", "E-mail" #110
Google Play Asks to Download app #120
functions shown don't work on device - vivo.sx: cannot "Add files" (videos) site #108

### Device information

* Echo Show device 2nd gen
* Firefox version: 1.2

**Comment by mcomella** [comment]
Closing in favor of a single bug to handle this issue, #85.
