### ISSUE TITLE
Investigation: Tracking Usage outside YouTube

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-echo-show#151]
### Why/User Benefit/User Problem

Determine how many people & sessions use Firefox for things outside YouTube, to help with feature & bug prioritization

### What / Requirements

Determine how we can track the following without sacrificing user privacy or our current policy
* the count & percent of users that browse outside YouTube

### Acceptance Criteria (how do I know when I’m done?)

* A Github issue is created for additional tracking needed
* A plan with data team in place to dashboard the results

**Comment by athomasmoz** [comment]
Considerations
* When do we send this?

**Comment by athomasmoz** [comment]
Already done for Fire TV. Suggest looking at how that works.

**Comment by Baron-Severin** [comment]
Noting that this was recently completed in FFTV under story https://github.com/mozilla-mobile/firefox-tv/issues/1620.  I'm borrowing code from that PR.

@athomasmoz @Sdaswani with @liuche on PTO, who should I tag for the data review?

**Comment by Sdaswani** [comment]
@Baron-Severin per https://wiki.mozilla.org/Firefox/Data_Collection, you should be able to fire off an email to group e-mail on that page and be assigned a data peer.
