### ISSUE TITLE
Refactor activeScreen to MVVM architecture

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-echo-show#176]
### Why/User Benefit/User Problem
In order to prevent regressions and make quick changes, our code needs to be easy to change. For the the code to be easy to change, we need to make our code patterns predictable and easy to test. Our solution for that on Fire TV is to have a defined architecture. To get an architecture on Echo Show, we should do it incrementally.

To fix #167, I attempted to refactor to MVVM and it's been taking too long so I created this follow-up.

**Comment by mcomella** [comment]
I pushed my WIP to upstream: https://github.com/mozilla-mobile/firefox-echo-show/tree/176-mcomella-mvvm-activescreen

This won't apply cleanly because I've fixed bugs and incrementally added some ViewModels.

**Comment by athomasmoz** [comment]
This would be great to do, but became a bit of a rabbit hole. Closing for now, but may look at in future.
