### ISSUE TITLE
Remove domain lists from assets?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/firefox-echo-show#182]
The app seems to use the `browser-domains` component:
https://github.com/mozilla-mobile/firefox-echo-show/blob/master/app/build.gradle#L139

However it still has the domain lists in the assets folder:
https://github.com/mozilla-mobile/firefox-echo-show/tree/master/app/src/main/assets/domains

I assume they can get removed? To make use of the list in the components that's probably required.

**Comment by mcomella** [comment]
Thanks Sebastian.

Quickly skimming:
- The app compiles without the domains in the assets folder
- The app does not seem to use ^
- The app seems to function correctly without it
