### ISSUE TITLE
Allow Proguard to remove unused @JavascriptInterface with WebView

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-echo-show#206]
Generated in the default `proguard-rules.pro`. Uncomment https://github.com/mozilla-mobile/firefox-tv/blob/master/app/proguard-rules.pro#L23

**Comment by mcomella** [comment]
@psymoon Is this to remove unused `@javascriptInterface` or to prevent unused methods, e.g. like the ones in `@javascriptInterface` from being removed?

In any case, this seems fragile (need fully-qualified class names of classes with `@JavascriptInterface` so if it's working now without these lines of code, I'm hesitant to add them.

**Comment by psymoon** [comment]
@mcomella: I think proguard obfuscates android internal classes as well. We need to verify other `webview` operations that rely on internal JS work correctly in both release and debug builds.  We definitely don't want `public *;` though. Possibly related - https://github.com/mozilla-mobile/firefox-tv/issues/1758

**Comment by mcomella** [comment]
Trying to close on FFTV: https://github.com/mozilla-mobile/firefox-tv/issues/1705 Will follow suit here.

**Comment by mcomella** [comment]
Closing like the Fire TV issue: see there for details.
