### ISSUE TITLE
Keyboard is broken on 'Search with Google' tile

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-echo-show#213]
## Steps to reproduce
- From home screen
- Select 'Search with Google' tile
- Enter search query

### Expected behavior
- Letters appear in TextView as typed
- Hitting the checkmark button should initiate a search

### Actual behavior
- Interacting with the keyboard has no effect
- Unable to search

### Device information

* Echo Show device: 2nd gen
* Firefox version: eafecb05a1723f31e7702cddfcc7e103965a09ef

**Comment by mcomella** [comment]
Filed #214 to add a regression test.

**Comment by Baron-Severin** [comment]
Issue is introduced somewhere between 1e823674 (working) and a66f8ed8 (failing), a space of around ten commits.

My wild guess is that it was introduced by f775e9060f1d755a80d90a367a993478ca4a6857: "Closes #162: Prevent a11y from focusing hidden EditText."

The hidden EditText is used to store typed text, so that seems a likely point to start investigating.

**Comment by Baron-Severin** [comment]
f775e9060f1d755a80d90a367a993478ca4a6857 makes our hidden EditText unfocusable so that VoiceView will not focus it.  Unfortunately, we currently retrieve text for 'Search with Google' by manually showing the soft keyboard and requesting focus on this hidden EditText.  Making it unfocusable therefore breaks 'Search with Google'.

**Comment by kglazko** [comment]
Added testcase regarding Search with Google: https://testrail.stage.mozaws.net/index.php?/cases/view/235390&group_by=cases:section_id&group_order=asc&group_id=21826

**Comment by mcomella** [comment]
QA: Please make sure the google search button is working as expected. Additionally, with VoiceView on, in previous fixes, we'd notice that if you:
- Click google search tile
- Press back to close keyboard
- Focus a home tile
- Swipe to linear navigate

Sometimes the swipe to linear navigate would advance to the next tile and return to the currently focused tile, announcing both. Instead, it should only have advanced to the next tile (i.e. the normal behavior).

**Comment by kglazko** [comment]
I can't reproduce this in the latest build.
