### ISSUE TITLE
Screen flickers after navigating away from home page either on first use or after clearing data

### ISSUE THREAD

**Issue by kglazko** [mozilla-mobile/firefox-echo-show#218]
## Steps to reproduce
1. Open Firefox
2. If first time use:
- Click on a default tile such as Wikipedia OR
- Click on URL, enter URL and go OR
- Click on Settings then About
3. If not first time use:
- Go to settings and clear data
- Go to home page
- Click on a default tile such as Wikipedia OR
- Click on URL, enter URL and go OR
- Click on Settings then About
### Expected behavior
You will navigate to the new page in a manner that is visually similar to existing browser experiences
### Actual behavior
The screen will flicker and even appear to jerk up and down as it loads the new page
### Device information

* Echo Show device 2nd Gen
* Firefox version Latest Build (Says 1.2, but we call it 1.3)

**Comment by mcomella** [comment]
I can't reproduce this on my gen 2, gen 1, or emulator, even using the build I sent kglazko.

@kglazko What is your OS version? Can you reproduce if you build off of master? What is your user agent?

My gen 2 is:
- OS version: 620524210
- Chrome 59.0.3071

In any case, I think what is happening is that the WebView is using an empty graphics buffer until we load a page. Maybe this only happens on newer versions of the WebView?

**Comment by kglazko** [comment]
OS: 628539520
Can you clarify what Chrome represents in this case? I was having troubles creating a signed build; can you send the one you would want me to use?

**Comment by mcomella** [comment]
> OS: 628539520

It's newer, as I expected! 😨 

> Can you clarify what Chrome represents in this case?

@kglazko It's the part of the user agent that I'm most interested in – the Chrome version. Can you share that version, or the whole user agent?

> I was having troubles creating a signed build; can you send the one you would want me to use?

You should be able to create debug builds: either use the "Build Variants" menu in the left side pane to select the amazonWebViewDebug or with gradle `./gradlew assembleamazonwebviewdebug installamazonwebviewdebug`

That being said, I expect it's the OS version that's the problem.

**Comment by mcomella** [comment]
Action item: watch the video to figure out what's going on.

It's curious that this is an issue: on the initial homescreen, we actually have a grey view behind the navigation overlay. Maybe it's happening because we start to alpha transition the view away when the overlay slides out? I wonder what the WebView visibility is here.

**Comment by mcomella** [comment]
I have two fixes in mind: waiting on MTV to test them out.

**Comment by kglazko** [comment]
Cannot reproduce issue with latest build @mcomella
