### ISSUE TITLE
Non-intuitive how to search from non-initial screen

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-echo-show#25]
https://github.com/mozilla-mobile-skunkworks/firefox-connect/issues/219

**Comment by athomasmoz** [comment]
@aminalhazwani is this still a concern?

**Comment by mcomella** [comment]
[via Slack](https://mozilla.slack.com/archives/CDBC2QMUY/p1542277718095100), we're looking to see if, using existing data, we know how often the user searches from the toolbar on the non-initial homescreen and how often they click the Google search tile from the non-initial homescreen (but we don't have telemetry for that):

> amin [39 minutes ago]
> Oki, from what I can see on telemetry we have a decent amount of taps on home tiles, home button, type query and type url so my assumption is that search is still accessible from non-intial screen. @mcomella do you think there’s data to back up this assumption?
>
>
> mcomella [< 1 minute ago]
> _maybe_. If it’s possible to correlate sequential events, we could check “User received load event on homescreen (tile, query, url); user did stuff; user did type_query”.
>
> I don’t know if this is possible though.

@mmccorks  Do you know?

**Comment by athomasmoz** [comment]
It's not clear if this is causing an issue for users. But we now have the Google search tile, which can be used if it's not clear that the URL bar can be typed in. Closing
