### ISSUE TITLE
Enable MediaSession permission on Echo Show

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-echo-show#306]
### Why/User Benefit/User Problem
Echo Show will get MediaSession features (voice control for play, pause, etc)

### What / Requirements
- Add [MediaSession permission](https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/AndroidManifest.xml#L14)

### Acceptance Criteria (how do I know when I’m done?)
- Voice MediaSession permission is enabled
- Build created & uploaded

**Comment by liuche** [comment]
@athomasmoz moving this here to the top to be prioritized!

**Comment by mcomella** [comment]
After this PR, I noticed no difference in the UX:
- "Alexa pause" does not pause the video before or after the PR
- Alexa does not provide "unknown command" feedback before or after the PR

**Comment by npark-mozilla** [comment]
@mcomella 'Alexa pause' pauses the video on echo 5 only, but it doesn't respond to 'Alexa play' or any other media command.  On Echo 2, it pauses to process, but resumes after.  Should I raise a separate bug?

**Comment by mcomella** [comment]
@npark-mozilla My understanding is that adding this permission wasn't intended to make Alexa voice commands work on these devices yet so I don't know if another issue is necessary until it's available in the platform.

@athomasmoz What do you think?

**Comment by athomasmoz** [comment]
Yep, that's correct. The voice commands aren't currently supported.
