### ISSUE TITLE
ES gen 2: Google home tile has black text instead of white

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-echo-show#311]
## Steps to reproduce
- Open app

### Expected behavior
Google home tile text is white

### Actual behavior
Home tile text is black.

![image](https://user-images.githubusercontent.com/759372/65917510-573c3180-e38c-11e9-91c4-f0679de0016b.png)

### Device information
* Echo Show device (1st gen, 2nd gen, or 5): 2nd. Unable to repro on 5. 1st gen untested.
* Latest affected Firefox version: v1.3 master 2083e53e6cb81c35ba0692a59baaf4ae13ddd5fc
* Earliest affected Firefox version: ?

**Comment by mcomella** [comment]
I'm unable to reproduce this on master or the commit referenced in the STR. I tried:
- "Echo go home. Echo open Firefox"
- Force-stopping and "Echo open Firefox"
- Loading a page, "Echo go home" (to session restore the page), force-stopping, "Echo open Firefox", clicking the menu button

Maybe 3 times each to check for race conditions and I was still unable to reproduce.

I'm going to close as WORKSFORME, expecting that if this is a real issue, we'll catch it during QA. My best guess is that this is the result of a race condition (our fault) or an intermittent hardware issue (not our fault).

**Comment by mcomella** [comment]
QA: please verify this doesn't happen in your testing. I was personally unable to reproduce this problem when I retested.

**Comment by npark-mozilla** [comment]
I could not reproduce this on 2 or 5.  Closing.
