### ISSUE TITLE
Follow-up: selectively enable elevation on working devices

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-echo-show#314]
### Vision statement / What / Requirements
A side effect of #305 was that the toolbar casted a shadow on the initial homescreen on all devices: 

![device-2019-09-30-141245](https://user-images.githubusercontent.com/759372/65919715-04fe0f00-e392-11e9-8c42-4cbe9ccfe7f5.png)

I realized we can check each device in code to selectively enable it on the known working devices.

**Comment by mcomella** [comment]
QA: please verify the same steps as https://github.com/mozilla-mobile/firefox-echo-show/issues/305#issuecomment-536768783. Also, as depicted in the screenshot of the bug for this PR, on the initial homescreen there should be a shadow on the ES5 but not on the ES 1st gen or 2nd gen.

**Comment by npark-mozilla** [comment]
@mcomella Seems the opposite - there is a shadown on Echo 2 (the big screen one), but only a line dividing the toolbar and the bottom panel on ES 5 (small screen device)

**Comment by npark-mozilla** [comment]
Echo 5:
![IMG_20191010_150609](https://user-images.githubusercontent.com/6930774/66598777-ca555d00-eb6f-11e9-9f57-6e3b6c03c998.jpg)
Echo 2:
![IMG_20191010_150613](https://user-images.githubusercontent.com/6930774/66598798-d6411f00-eb6f-11e9-8b5d-4a34811786ab.jpg)

**Comment by mcomella** [comment]
@npark-mozilla This looks like I'd expect.

**Comment by npark-mozilla** [comment]
Thanks!
