### ISSUE TITLE
Echo responds to 'Alexa pause' only for video commands (on Echo 5)

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-echo-show#316]
## Steps to reproduce
Open a video, (youtube) make it fullscreen
Say 'Alexa, pause'

### Expected behavior
Video is paused, and 'Alexa, play' should resume playback
### Actual behavior
Video is paused on echo 5 only.  And no other voice command works to resume the video

### Device information
* Echo Show device (1st gen, 2nd gen, or 5): 2,5
* Latest affected Firefox version: master
* Earliest affected Firefox version: ?

**Comment by athomasmoz** [comment]
This is expected behaviour
