### ISSUE TITLE
Verify google search adjusts to locales appropriately

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-echo-show#37]
https://github.com/mozilla-mobile-skunkworks/firefox-connect/issues/283

**Comment by athomasmoz** [comment]
@aminalhazwani do you mind testing this out for us?

**Comment by aminalhazwani** [comment]
I initially had the device OS set to English, with Firefox set to English too. This is what we see if we do a Google search.

<img width="1605" alt="image" src="https://user-images.githubusercontent.com/1721875/48617833-cc329280-e997-11e8-9da8-6a62060540c9.png">

Results/UI are in German but the language popup is off the screen.

I then set the OS to German, the Echo Show rebooted but Firefox was still set to English. Here an example, German button "Fertig" but placeholders and texts are still in German.

<img width="1531" alt="image" src="https://user-images.githubusercontent.com/1721875/48617939-13b91e80-e998-11e8-8810-1b50bfd565eb.png">

Triggering a search then did not displayed the language popup.

<img width="1657" alt="image" src="https://user-images.githubusercontent.com/1721875/48618012-4c58f800-e998-11e8-9d8e-f1666a7102e9.png">

I then restarted the device once more and then Firefox was then set in German.

**Comment by mcomella** [comment]
So it looks like Google gates by IP but investigates the browser's locale to provide prompts to switch.

I think this is working as best as we can expect: @athomasmoz Should we close?

> I then set the OS to German, the Echo Show rebooted but Firefox was still set to English.

I filed #141.

**Comment by athomasmoz** [comment]
Yep, sounds good. Thanks for the investigation @aminalhazwani !
