### ISSUE TITLE
Handle startup time telemetry in dashboards

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-echo-show#78]
https://github.com/mozilla-mobile-skunkworks/firefox-connect/issues/491

**Comment by athomasmoz** [comment]
@mmccorks do you already have this on your backlog? Or should I create an item for it?

**Comment by mmccorks** [comment]
I can't see this ticket, I think I don't have access to the skunkworks repo anymore.

**Comment by athomasmoz** [comment]
Tracking under data team requests https://bugzilla.mozilla.org/show_bug.cgi?id=1509366
