### ISSUE TITLE
Remove unused resources (e.g. activity_info)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-echo-show#93]
https://github.com/mozilla-mobile-skunkworks/firefox-connect/issues/518

**Comment by mcomella** [comment]
**Update:** l10n has requested that we remove unused strings so we can have an understanding of the overlap of strings between Focus, Fire TV, and Echo Show. In order to do this, we also have to remove unused code because strings that are referenced in unused code will not be considered unused.

**Comment by athomasmoz** [comment]
Suggestion - may want to tackle FireTV at same time https://github.com/mozilla-mobile/firefox-tv/issues/1282

**Comment by mcomella** [comment]
@Delphine @Pike FYI that the unused strings were removed from FFES. FFTV still needs to have its strings removed: https://github.com/mozilla-mobile/firefox-tv/issues/1282

Note that we still rely on some features with strings, e.g. error pages, that we expect to eventually move to components.
